### ISSUE TITLE
Open3dmmBootstrapper runtime exceptions

### ISSUE THREAD

**Issue by frank-weindel** [Jayrod246/Open3dmm#1]
Hi Jayrod. I was browsing 3dmm.com for the first time in over 4 years and saw your thread. This looks really cool.

I've got this compiling in Visual Studio 2019 community edition and running on Windows 10. Initially I was getting access violation errors starting in the first memcpy in the bootstrapper, and it turned out that all of my **int**s were being interpreted as 32-bit types and all the pointer addresses were being truncated. Swapped out all the **int** with **long long** and that got me all the way through to the `hacky_function` call. But the function call is now giving me this exception:

```
Unhandled exception at 0x0000022E4B2A000A in Open3dmmBootstrapper.exe: 0xC0000096: Privileged instruction.
```

Any ideas? It's been awhile since I've done any serious C++, so apologies if I'm missing something.

**Comment by Jayrod246** [comment]
I cloned the project as is to reproduce the problem. 
1. NuGet packages must be restored by right-clicking the solution -> Restore NuGet Packages.
2. It seems to select x64 by default. You need to change the target architecture to x86.
3. In Open3dmmBootstrapper.cpp, you may need to modify this part:
`std::memcpy((void*)((int)str_dest + 80), "C:\\microsoft kids\\3d movie maker\\3dmovie.exe", 45);`
to point to the path of where you installed 3dmm, the constant 45 is the length of the path string and will need to be changed as well. In future I need to write a registry lookup that finds the 3dmm install path automatically.
4. Build the solution. The bootstrapper exe is copied to the dll output directory. Before running, go to the Open3dmm dll project properties, under debug, set Start action to Start external program: `.\Open3dmm\bin\x86\Debug\Open3dmmBootstrapper.exe`
5. Now with Open3dmm as startup project, it should allow you to debug the application.
If you get this exception: Managed Debugging Assistant 'LoaderLock'
You have to uncheck Break when this exception type is thrown and hit continue.

Need to see if all this configuration can simply be pushed to the repo so it doesn't have to be done every time.

**Comment by frank-weindel** [comment]
Great! I've gotten passed all the exceptions. Now I can see 3DMM starting, but now I'm getting an error message box from 3dmm: "3D Movie Maker could not start. You may need to run Setup again." I installed 3DMM via the installer. The program loads normally by itself.

**Comment by Jayrod246** [comment]
I'll have to figure out what's happening because I'm having the same problem when I installed from the original setup/disc. In the meantime, you could try the modern installer in this thread: https://3dmm.com/showthread.php?t=17038

This is what I use for my setup and oddly enough it works.

**Comment by frank-weindel** [comment]
Awesome.  I was  experimenting with commenting out most of the hooks, etc, and it still happened. Maybe its something the original installer sets in the registry? Using the modern installer after the original still gave me the error. But after I uninstalled the original and reinstalled with the modern one, it worked! Are the 3d objects supposed to look like this right now? 

![open3dmm-success](https://user-images.githubusercontent.com/6070611/57744212-4ec1b380-7696-11e9-82bb-4551b0786ba8.png)

We should chat sometime soon about where this project is at the moment and what things you'd like help with next. I'd like to help if I can.

**Comment by mdtauk** [comment]
When the renderer is in a good state, you should consider how you would modernise the controls and UI.

Will it remain a Win32 project, or could it migrate to DirectX, UWP, Hololens?

**Comment by Jayrod246** [comment]
>  Are the 3d objects supposed to look like this right now?

Yes, that's how I've got them looking atm. Right now I'm reversing GUI functions so that I can render buttons and menus in the correct order, eg. menus appear in the foreground.

> We should chat sometime soon about where this project is at the moment and what things you'd like help with next. I'd like to help if I can.

I appreciate any help you can provide! Currently I'm just rewriting functions in c#, focusing on the user interface now, and hooking them in place of the native ones. Eventually I hope to rewrite enough of the program that it can run standalone, and all the native calls/hooking can be removed.

> Will it remain a Win32 project, or could it migrate to DirectX, UWP, Hololens?

It could. Portability is a hope I have in mind for when the native layer is completely abstracted out. But I won't be concerned with that so much until further down the road. Other developers are more than welcome to start work on features like this though!
