### ISSUE TITLE
Chat Room

### ISSUE THREAD

**Issue by frank-weindel** [Jayrod246/Open3dmm#3]
I've been spending a bit of time playing around and deciphering your code so far and it'd be a great to have a Slack or similar chat set up so we can coordinate (and I can ask questions 😄). Let me know if you'd like me to set something up.

**Comment by Jayrod246** [comment]
Okay, I made a discord server open for anyone to join: [https://discord.gg/wjKqZCV](https://discord.gg/wjKqZCV). I'll do my best to be helpful.
