### ISSUE TITLE
Mono support?

### ISSUE THREAD

**Issue by neuromancer** [Jayrod246/Open3dmm#4]
I wonder if this will work on Mono, so it can be used in other platforms like Linux.

**Comment by Jayrod246** [comment]
I'm actually targeting .Net Core/Standard in my local repo and using [Veldrid](https://github.com/mellinoe/veldrid), yet another cross platform library that will allow open3dmm to eventually run on other such platforms as Linux.

**Comment by neuromancer** [comment]
Neat! I'm closing this issue then. Please let me know when this can be tested in Linux so I can give a try. :smile:
